<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnterpriseWms.Contracts\EnterpriseWms.Contracts.csproj" />
    <ProjectReference Include="..\EnterpriseWms.Domain\EnterpriseWms.Domain.csproj" />
  </ItemGroup>

</Project>
